-- Oracle RPT bootstrap DDL (initial scaffold)
-- Run as a user that can create objects in schema RPT.

-- Optional: create schema user (DBA only)
-- CREATE USER RPT IDENTIFIED BY "<strong_password>";
-- GRANT CONNECT, RESOURCE TO RPT;
-- ALTER USER RPT QUOTA UNLIMITED ON USERS;

-- Workflow jobs
CREATE TABLE RPT.WORKFLOW_JOBS (
    ID               VARCHAR2(36)       NOT NULL,
    PSR_NUMBER       VARCHAR2(128)      NOT NULL,
    STATUS           VARCHAR2(32)       NOT NULL,
    SQL_TEXT         CLOB               NOT NULL,
    TARGET_DB_KIND   VARCHAR2(32)       NOT NULL,
    PII_SUMMARY      CLOB,
    PERFORMANCE_NOTES CLOB,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_WORKFLOW_JOBS PRIMARY KEY (ID)
);

CREATE INDEX RPT.IX_WORKFLOW_JOBS_STATUS ON RPT.WORKFLOW_JOBS (STATUS);
CREATE INDEX RPT.IX_WORKFLOW_JOBS_PSR ON RPT.WORKFLOW_JOBS (PSR_NUMBER);

-- TTL-controlled report grants for backend authorization checks
CREATE TABLE RPT.REPORT_GRANTS (
    GRANT_ID         VARCHAR2(36)       NOT NULL,
    REPORT_ID        VARCHAR2(128)      NOT NULL,
    SUBJECT_ID       VARCHAR2(256)      NOT NULL,
    DOMAIN_ID        VARCHAR2(128)      NOT NULL,
    ACTION           VARCHAR2(32)       DEFAULT 'read' NOT NULL,
    VALID_UNTIL      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_REPORT_GRANTS PRIMARY KEY (GRANT_ID)
);

CREATE INDEX RPT.IX_REPORT_GRANTS_LOOKUP
    ON RPT.REPORT_GRANTS (REPORT_ID, SUBJECT_ID, DOMAIN_ID, ACTION, VALID_UNTIL);

-- Reference view for PII metadata (source is enterprise metadata system).
-- Replace BASE_META_TABLE with your actual source object or synonym.
-- Expected columns: OWNER, TABLE_NAME, COLUMN_NAME, PII_YN
CREATE OR REPLACE VIEW RPT.VW_PII_META AS
SELECT
    OWNER,
    TABLE_NAME,
    COLUMN_NAME,
    PII_YN
FROM RPT.BASE_META_TABLE;

-- Trigger to auto-refresh UPDATED_AT
CREATE OR REPLACE TRIGGER RPT.TRG_WORKFLOW_JOBS_UPD
BEFORE UPDATE ON RPT.WORKFLOW_JOBS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
