-- Oracle RPT bootstrap DDL (initial scaffold)
-- Run as a user that can create objects in schema RPT.

-- Optional: create schema user (DBA only)
-- CREATE USER RPT IDENTIFIED BY "<strong_password>";
-- GRANT CONNECT, RESOURCE TO RPT;
-- ALTER USER RPT QUOTA UNLIMITED ON USERS;

-- Workflow jobs
CREATE TABLE RPT.TB_RPT_WORKFLOW_JOBS (
    ID               VARCHAR2(36)       NOT NULL,
    PSR_NUMBER       VARCHAR2(128)      NOT NULL,
    STATUS           VARCHAR2(32)       NOT NULL,
    SQL_TEXT         CLOB               NOT NULL,
    TARGET_DB_KIND   VARCHAR2(32)       NOT NULL,
    PII_SUMMARY      CLOB,
    PERFORMANCE_NOTES CLOB,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_RPT_WORKFLOW_JOBS PRIMARY KEY (ID)
);

CREATE INDEX RPT.IX_TB_RPT_WORKFLOW_JOBS_STATUS ON RPT.TB_RPT_WORKFLOW_JOBS (STATUS);
CREATE INDEX RPT.IX_TB_RPT_WORKFLOW_JOBS_PSR ON RPT.TB_RPT_WORKFLOW_JOBS (PSR_NUMBER);

-- TTL-controlled report grants for backend authorization checks
CREATE TABLE RPT.TB_RPT_REPORT_GRANTS (
    GRANT_ID         VARCHAR2(36)       NOT NULL,
    REPORT_ID        VARCHAR2(128)      NOT NULL,
    SUBJECT_ID       VARCHAR2(256)      NOT NULL,
    DOMAIN_ID        VARCHAR2(128)      NOT NULL,
    ACTION           VARCHAR2(32)       DEFAULT 'read' NOT NULL,
    VALID_UNTIL      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_RPT_REPORT_GRANTS PRIMARY KEY (GRANT_ID)
);

CREATE INDEX RPT.IX_TB_RPT_REPORT_GRANTS_LOOKUP
    ON RPT.TB_RPT_REPORT_GRANTS (REPORT_ID, SUBJECT_ID, DOMAIN_ID, ACTION, VALID_UNTIL);

-- NOTE:
-- PII view creation moved to consolidated bootstrap file:
--   backend/sql/000_bootstrap_rpt.sql
-- (Requires TB_RPT_PII_METADATA to exist first)

-- Trigger to auto-refresh UPDATED_AT
CREATE OR REPLACE TRIGGER RPT.TRG_TB_RPT_WORKFLOW_JOBS_UPD
BEFORE UPDATE ON RPT.TB_RPT_WORKFLOW_JOBS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
