ALTER TABLE RPT.TB_RPT_WORKFLOW_JOBS ADD (
    REQUEST_TITLE      VARCHAR2(256),
    REQUESTER_EMP_NO   VARCHAR2(64),
    REQUESTER_NAME     VARCHAR2(128),
    REQUESTER_DEPT     VARCHAR2(128),
    DEVELOPER_EMP_NO   VARCHAR2(64),
    DEVELOPER_NAME     VARCHAR2(128),
    DEVELOPER_DEPT     VARCHAR2(128)
);
