CREATE TABLE RPT.TB_RPT_MASK_POLICY (
    POLICY_ID        VARCHAR2(36)      NOT NULL,
    POLICY_NAME      VARCHAR2(128)     NOT NULL,
    TRANSFORM_KEY    VARCHAR2(32)      NOT NULL,
    USE_YN           CHAR(1)           DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_RPT_MASK_POLICY PRIMARY KEY (POLICY_ID),
    CONSTRAINT CK_TB_RPT_MASK_POLICY_USEYN CHECK (USE_YN IN ('Y','N'))
)
TABLESPACE TS_RPT_DAT;

CREATE OR REPLACE TRIGGER RPT.TRG_TB_RPT_MASK_POLICY_UPD
BEFORE UPDATE ON RPT.TB_RPT_MASK_POLICY
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

INSERT INTO RPT.TB_RPT_MASK_POLICY (POLICY_ID, POLICY_NAME, TRANSFORM_KEY, USE_YN)
VALUES (SYS_GUID(), '주민등록번호 정책', 'RRN', 'Y');
INSERT INTO RPT.TB_RPT_MASK_POLICY (POLICY_ID, POLICY_NAME, TRANSFORM_KEY, USE_YN)
VALUES (SYS_GUID(), '전화번호 정책', 'PHONE', 'Y');
INSERT INTO RPT.TB_RPT_MASK_POLICY (POLICY_ID, POLICY_NAME, TRANSFORM_KEY, USE_YN)
VALUES (SYS_GUID(), '기본주소 정책', 'ADDRESS', 'Y');
INSERT INTO RPT.TB_RPT_MASK_POLICY (POLICY_ID, POLICY_NAME, TRANSFORM_KEY, USE_YN)
VALUES (SYS_GUID(), '성명(한글) 정책', 'NAME_KO', 'Y');
INSERT INTO RPT.TB_RPT_MASK_POLICY (POLICY_ID, POLICY_NAME, TRANSFORM_KEY, USE_YN)
VALUES (SYS_GUID(), '성명(영문) 정책', 'NAME_EN', 'Y');

COMMIT;
