-- App users, permission groups, per-page read/write matrix (write implies read).
-- Run as RPT owner.

CREATE TABLE RPT.TB_RPT_PERM_GROUP (
    GROUP_ID        VARCHAR2(36)       NOT NULL,
    GROUP_NAME      VARCHAR2(128)      NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    USE_YN          CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_RPT_PERM_GROUP PRIMARY KEY (GROUP_ID),
    CONSTRAINT CK_TB_RPT_PERM_GROUP_USEYN CHECK (USE_YN IN ('Y','N'))
)
TABLESPACE TS_RPT_DAT;

CREATE OR REPLACE TRIGGER RPT.TRG_TB_RPT_PERM_GROUP_UPD
BEFORE UPDATE ON RPT.TB_RPT_PERM_GROUP
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE TABLE RPT.TB_RPT_APP_USER (
    USER_ID         VARCHAR2(36)       NOT NULL,
    LOGIN_ID        VARCHAR2(128)      NOT NULL,
    PASSWORD_HASH   VARCHAR2(512)      NOT NULL,
    DISPLAY_NAME    VARCHAR2(128),
    TEAM_ID         VARCHAR2(64),
    GROUP_ID        VARCHAR2(36)       NOT NULL,
    USE_YN          CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_TB_RPT_APP_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_TB_RPT_APP_USER_LOGIN UNIQUE (LOGIN_ID),
    CONSTRAINT FK_TB_RPT_APP_USER_GROUP FOREIGN KEY (GROUP_ID)
        REFERENCES RPT.TB_RPT_PERM_GROUP (GROUP_ID),
    CONSTRAINT CK_TB_RPT_APP_USER_USEYN CHECK (USE_YN IN ('Y','N'))
)
TABLESPACE TS_RPT_DAT;

CREATE INDEX RPT.IX_TB_RPT_APP_USER_GROUP ON RPT.TB_RPT_APP_USER (GROUP_ID)
TABLESPACE TS_RPT_DAT;

CREATE TABLE RPT.TB_RPT_PERM_MATRIX (
    GROUP_ID        VARCHAR2(36)       NOT NULL,
    PAGE_KEY        VARCHAR2(64)       NOT NULL,
    CAN_READ        CHAR(1)            DEFAULT 'N' NOT NULL,
    CAN_WRITE       CHAR(1)            DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_TB_RPT_PERM_MATRIX PRIMARY KEY (GROUP_ID, PAGE_KEY),
    CONSTRAINT FK_TB_RPT_PERM_MATRIX_GROUP FOREIGN KEY (GROUP_ID)
        REFERENCES RPT.TB_RPT_PERM_GROUP (GROUP_ID),
    CONSTRAINT CK_TB_RPT_PERM_MATRIX_READ CHECK (CAN_READ IN ('Y','N')),
    CONSTRAINT CK_TB_RPT_PERM_MATRIX_WRITE CHECK (CAN_WRITE IN ('Y','N'))
)
TABLESPACE TS_RPT_DAT;

COMMIT;
