-- DML 권한: 읽기 전용 롤 / 쓰기 롤 분리 (DDL 없음).
-- RPT 스키마 소유자로 실행 후, 앱 서비스 계정에 RL_RPT_R·RL_RPT_W 를 부여하면 됩니다.

GRANT SELECT ON RPT.TB_RPT_PERM_GROUP TO RL_RPT_R;
GRANT INSERT, UPDATE, DELETE ON RPT.TB_RPT_PERM_GROUP TO RL_RPT_W;

GRANT SELECT ON RPT.TB_RPT_APP_USER TO RL_RPT_R;
GRANT INSERT, UPDATE, DELETE ON RPT.TB_RPT_APP_USER TO RL_RPT_W;

GRANT SELECT ON RPT.TB_RPT_PERM_MATRIX TO RL_RPT_R;
GRANT INSERT, UPDATE, DELETE ON RPT.TB_RPT_PERM_MATRIX TO RL_RPT_W;

GRANT SELECT ON RPT.TB_RPT_DEPT TO RL_RPT_R;
GRANT INSERT, UPDATE, DELETE ON RPT.TB_RPT_DEPT TO RL_RPT_W;

COMMIT;
