-- 부서 마스터 + APP 사용자 DEPT_ID (이름 변경은 DEPT_NAME만 수정).
-- RPT 소유자로 실행.

CREATE TABLE RPT.TB_RPT_DEPT (
    DEPT_ID         VARCHAR2(36)       NOT NULL,
    DEPT_CODE       VARCHAR2(32)       NOT NULL,
    DEPT_NAME       VARCHAR2(128)      NOT NULL,
    USE_YN          CHAR(1)            DEFAULT 'Y' NOT NULL,
    CREATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_RPT_DEPT PRIMARY KEY (DEPT_ID),
    CONSTRAINT UQ_TB_RPT_DEPT_CODE UNIQUE (DEPT_CODE),
    CONSTRAINT CK_TB_RPT_DEPT_USEYN CHECK (USE_YN IN ('Y','N'))
)
TABLESPACE TS_RPT_DAT;

CREATE OR REPLACE TRIGGER RPT.TRG_TB_RPT_DEPT_UPD
BEFORE UPDATE ON RPT.TB_RPT_DEPT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

INSERT INTO RPT.TB_RPT_DEPT (DEPT_ID, DEPT_CODE, DEPT_NAME, USE_YN)
VALUES (SYS_GUID(), 'platform', '플랫폼', 'Y');
INSERT INTO RPT.TB_RPT_DEPT (DEPT_ID, DEPT_CODE, DEPT_NAME, USE_YN)
VALUES (SYS_GUID(), 'fin', '재무', 'Y');
INSERT INTO RPT.TB_RPT_DEPT (DEPT_ID, DEPT_CODE, DEPT_NAME, USE_YN)
VALUES (SYS_GUID(), 'hr', '인사', 'Y');
INSERT INTO RPT.TB_RPT_DEPT (DEPT_ID, DEPT_CODE, DEPT_NAME, USE_YN)
VALUES (SYS_GUID(), 'sec', '정보보호', 'Y');

ALTER TABLE RPT.TB_RPT_APP_USER ADD (DEPT_ID VARCHAR2(36));

UPDATE RPT.TB_RPT_APP_USER u
SET DEPT_ID = (
    SELECT d.DEPT_ID FROM RPT.TB_RPT_DEPT d
    WHERE d.DEPT_CODE = LOWER(TRIM(u.TEAM_ID)) AND ROWNUM = 1
)
WHERE u.DEPT_ID IS NULL AND u.TEAM_ID IS NOT NULL;

UPDATE RPT.TB_RPT_APP_USER u
SET DEPT_ID = (SELECT MIN(d.DEPT_ID) FROM RPT.TB_RPT_DEPT d WHERE d.DEPT_CODE = 'platform')
WHERE u.DEPT_ID IS NULL;

ALTER TABLE RPT.TB_RPT_APP_USER
    ADD CONSTRAINT FK_TB_RPT_APP_USER_DEPT FOREIGN KEY (DEPT_ID)
    REFERENCES RPT.TB_RPT_DEPT (DEPT_ID);

CREATE INDEX RPT.IX_TB_RPT_APP_USER_DEPT ON RPT.TB_RPT_APP_USER (DEPT_ID)
TABLESPACE TS_RPT_DAT;

COMMIT;
